echo "We are trying this practical from linux EC2"
echo "We are from batch-24 and learning git/gihub"
echo "Happy weekend"
echo "Hello batch-24, We are learning git"
echo "Please complete your practicals on daily basis"
echo "hi good morning this is mayruesh"
echo "this is test code"
echo "this is to check about branches update"
echo "my name is mayuresh"
echo "Hello world"
echo "this is new world"
echo "my name is khan"